ARG FROM_CONTAINER_IMAGE

FROM $FROM_CONTAINER_IMAGE
    
ENV DISPLAY=":1" \
    SCREEN_RESOLUTION="1024x768" 

RUN apk update; \
    apk add --no-cache bash xvfb terminus-font openbox tint2 xterm x11vnc ;\
    rm -rf /var/cache/apk/* /tmp/* /sbin/halt /sbin/poweroff /sbin/reboot /tmp/winetricks-${WINETRICKS_VERSION}

SHELL ["/bin/bash", "-c"]
EXPOSE 5900

COPY --chmod=0777 container-entrypoint /container-entrypoint

ENTRYPOINT ["/container-entrypoint"]
CMD [ "xterm" ]