name: Build and Push docker image to Docker Hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       -  name: Set up QEMU
          uses: docker/setup-qemu-action@v2
       -  name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
       -  name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
       -  name: Build and push X64
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: brpedromaia/openbox-vnc-lightweight:v${{github.run_number}},brpedromaia/openbox-vnc-lightweight:latest
            file: "./ContainerFile"
            build-args: FROM_CONTAINER_IMAGE=alpine:3.17.1
       -  name: Build and push X86
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: brpedromaia/openbox-vnc-lightweight:v${{github.run_number}}-i386,brpedromaia/openbox-vnc-lightweight:latest-i386
            file: "./ContainerFile"
            build-args: FROM_CONTAINER_IMAGE=i386/alpine:3.17.1